- venue: "FCS 2024"
  role: "Program Committee"
- venue: "MFPS 2024"
  role: "External Reviewer"
- venue: "FSCD 2024"
  role: "External Reviewer"
- venue: "POPL 2023"
  role: "PC Meeting Virtualization"
- venue: "OOPSLA 2022"
  role: "PC Meeting Virtualization"
